config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#home'

  get '/error' => 'visitors#error', as: 'error'
  get '/whatsmyip' => 'visitors#ip_address', as: 'ip_address'
  get '/visitor/signin' => 'visitors#signin', as: :signin_page
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/error' => 'visitors#error'
  get '/home' => 'visitors#index', as: "home"
  get '/auth/failure' => 'sessions#failure'

  get "/paypal_success" => "users#paypal_success", as: "paypal_success"
  get "/paypal_failed" => "users#paypal_failed", as: "paypal_failed"

  post '/users/me' => 'users#show'

  get "/current" => "pageants#current", as: "current_pageants"
  get "/past" => "pageants#past", as: "past_pageants"
  get "/all" => "pageants#all", as: "all_pageants"
  get "/pageants/current" => redirect("/current")
  get "/pageants/past" => redirect("/past")
  get "/pageants/all" => redirect("/all")

  resources :users, except: [:new, :delete] do
    collection do
      post :go_premium
      post :buy_votes
    end
    member do
      get :account
      get :register_premium
      post :block
      post :unblock
      post :withdraw
      post :give_bonus
    end
  end

  resources :withdrawals, only: [:index] do
    collection do
      post :complete
      post :reject
    end
    member do
      post :approve
    end
  end

  resources :settings, only: [] do
    collection do
      get :edit
      post :update
    end
  end

  resources :transactions, only: [:create]

  get '/info/:id' => 'contents#show', as: :info
  resources :contents, only: [:index, :show, :edit, :update] do
    collection do
      post :upload_image
    end
  end

  resources :pageants do
    member do
      post :publish
      post :unpublish
    end
    resources :contestants, except: [:index] do
      member do
        post :boost_vote
        get :vote
        get :votes
        get :upload
        post :upload_process
        post :delete_photo
      end
    end
  end
end

app/models/contestant.rb
class Contestant < ActiveRecord::Base
  enum gender: [:female, :male]
  enum status: [:active, :deleted]

  after_create :record_activity

  belongs_to :pageant
  has_many :photos, dependent: :destroy
  has_many :votes, dependent: :destroy

  validates :number, :name, presence: true
  validates_uniqueness_of :number, conditions: -> { where(status: 0) }, scope: [:pageant_id, :gender, :status]

  scope :sort_by_number, ->{order("number ASC")}
  scope :not_deleted, ->{where.not(status: Contestant.statuses[:deleted])}
  accepts_nested_attributes_for :photos, :reject_if => :check_photos

  def check_photos(photo_attr)
    # Delete photo attribute in params when null
    return true if photo_attr['image'].nil?
    # Delete photo attribute in params when reached the limit
    return true if self.photos.count > 5
    return false

    #errors.add(:base, "You've reached the maximum upload photos.") if self.photos.count > 5
  end

  def photo
    photos.present? ? photos.first.image : nil
  end

  def sname
    "#{name} #{'-' if description.present?} #{description}".squeeze(" ").strip
  end

  def get_latest_vote(user)
    offset = user.vote_per_hour - 1
    contestants = pageant.male_and_female? ? pageant.contestants.send(gender) : pageant.contestants

    if contestants.present?
      return Vote.where(user: user, contestant_id: contestants.pluck(:id)).order(:created_at).offset(offset).last
    else
      return nil
    end
  end

  def add_boost_vote(request, user, bulk_vote)
    @user_agent = UserAgent.parse(request.env['HTTP_USER_AGENT']) if request.present?
    last_vote = self.get_latest_vote(user)
    self.votes.create(
      user_id: user.id,
      bought: true,
      quantity: bulk_vote.quantity,
      ip_address: @user_agent.present? ? request.remote_ip : "0.0.0.0",
      platform: @user_agent.present? ? @user_agent.platform : "PayPal",
      browser: @user_agent.present? ? "#{@user_agent.browser} v#{@user_agent.version}" : nil
    )
    self.pageant.user.wallet.add_amount(bulk_vote.commission)
    return true
  end

  def add_vote(request, user, force = false, bought = false)
    @user_agent = UserAgent.parse(request.env['HTTP_USER_AGENT']) if request.present?
    last_vote = self.get_latest_vote(user)
    create_vote = false

    if force
      self.votes.create(
        user_id: user.id,
        bought: bought,
        ip_address: @user_agent.present? ? request.remote_ip : "0.0.0.0",
        platform: @user_agent.present? ? @user_agent.platform : "PayPal",
        browser: @user_agent.present? ? "#{@user_agent.browser} v#{@user_agent.version}" : nil
      )
      self.pageant.user.wallet.add_amount(bought ? Vote::BLK_PRICE : Vote::REG_PRICE)
      return true
    else
      remaining_votes = self.pageant.available_votes_of_user(user, gender)
      if remaining_votes > 0
        self.votes.create(
          user: user,
          bought: bought,
          ip_address: @user_agent.present? ? request.remote_ip : "0.0.0.0",
          platform: @user_agent.present? ? @user_agent.platform : "PayPal",
          browser: @user_agent.present? ? "#{@user_agent.browser} v#{@user_agent.version}" : nil
        )
        self.pageant.user.wallet.add_amount(bought ? Vote::BLK_PRICE : Vote::REG_PRICE)
        return true
      else
        return false
      end
    end
  end

  def vote_warning(user, new_line = false)
    if user.premium?
      if pageant.male_and_female?
        msg = "You have already casted all your votes for #{gender} contestants."
      else
        msg = "You have already casted all your votes."
      end
    else
      msg = "You have already casted your vote."
    end
    msg += new_line ? "<br>" : " "
    msg += "You can vote again in this pageant tomorrow."
    unless user.premium?
      msg += "<br><a class='premium-button' href='/info/premium-membership'>Click here</a> "
      msg += "to be a premium user and get 5 votes a day."
    end
    return msg
  end

  def record_activity
    Activity.create(user: pageant.user, resource: self, created_at: created_at, updated_at: updated_at, action: 'created')
  end
end

app/controllers/contestants_controller.rb
class ContestantsController < ApplicationController
  before_filter :authenticate_user!, except: [:show]
  before_filter :get_pageant, except: [:vote, :boost_vote, :show]
  before_filter :get_pageant_public_access, only: [:votes, :show]

  def show
    if @pageant.published_status == "upcoming"
      @seconds_remaining = (@pageant.voting_start.to_time.in_time_zone(ENV['TIMEZONE']) - Time.now.in_time_zone(ENV['TIMEZONE'])).to_i
    else
      @seconds_remaining = (@pageant.voting_end.to_time.in_time_zone(ENV['TIMEZONE']) - Time.now.in_time_zone(ENV['TIMEZONE'])).to_i
    end
    @contestants = @pageant.contestants.not_deleted.sort_by_number

    if @contestant.present?
      @top_contestants = @pageant.top(10, @contestant.gender)
      @other_pageants = @pageant.other(4)
      @remaining_votes = user_signed_in? ? @pageant.available_votes_of_user(current_user, @contestant.gender) : 0
    end

    @boost_votes = PremiumDenomination.boost_votes
  end

  def votes
    redirect_to pageant_contestant_path(@pageant, @contestant) and return unless admin?
    @votes = @contestant.votes.order("created_at DESC")
    @q = @votes.search(params[:q])
    @votes = @q.result(distinct: true).page(params[:page])
  end

  def new
    @contestant = @pageant.contestants.new
    @contestant.number = @pageant.contestants.not_deleted.count + 1
  end

  def create
    @contestant = @pageant.contestants.new(contestant_params)
    @contestant.gender = @pageant.default_gender unless @pageant.male_and_female?
    if @contestant.save
      redirect_to pageant_contestant_path(@pageant, @contestant), notice: "You have added new contestant."
    else
      render :new
    end
  end

  def edit
    get_contestant
  end

  def update
    get_contestant
    if @contestant.update_attributes(contestant_params)
      Activity.create(user: current_user, resource: @contestant, action: "updated")
      redirect_to pageant_contestant_path(@pageant, @contestant), notice: "You have saved your changes."
    else
      render :edit
    end
  end

  def destroy
    get_contestant
    if @contestant.deleted!
      @contestant.update_attributes(number: nil)
      Activity.create(user: current_user, resource: @contestant, action: "deleted")
      redirect_to pageant_path(@pageant), notice: "You have deleted a contestant."
    else
      redirect_to :back
    end
  end

  def vote
    get_pageant_public_access
    get_contestant
    redirect_to pageant_contestant_path(@pageant, @contestant) and return if current_user.blocked? || blocked_ip?
    vote = @contestant.add_vote(request, current_user)
    if vote == true
      redirect_to pageant_contestant_path(@pageant, @contestant, voted: true), notice: "Thank you for voting #{@contestant.name}."
    else
      msg = @contestant.vote_warning(current_user)
      redirect_to pageant_contestant_path(@pageant, @contestant), alert: msg
    end
  end

  def boost_vote
    get_pageant_public_access
    get_contestant
    redirect_to pageant_contestant_path(@pageant, @contestant) and return if current_user.blocked? || blocked_ip?
    boost_vote = PremiumDenomination.find_by(code: params[:boost_vote])
    bulk_vote = current_user.bulk_votes.new(pageant: @pageant, contestant: @contestant, quantity: boost_vote.validity)
    transaction = current_user.premium_transactions.create(premium_denomination: boost_vote, price: boost_vote.price, quantity: boost_vote.validity)
    bulk_vote.premium_transaction = transaction
    if bulk_vote.save
      if transaction.setup!(paypal_success_url, paypal_failed_url)
        redirect_to transaction.redirect_uri
      else
        transaction.failed!
        redirect_to :back, alert: "Transaction failed. Please try again later."
      end
    else
      transaction.failed!
    end
  end

  def upload
    get_contestant
    @photo = @contestant.photos.build
  end

  def upload_process
    get_contestant
    if @contestant.update(contestant_photos_params)
      redirect_to pageant_contestant_path(@pageant, @contestant), notice: "You have uploaded new photo#{'s' if contestant_photos_params["photos_attributes"].count > 1}."
    else
      redirect_to :back, alert: @contestant.errors.full_messages.join(", ")
    end
  end

  def delete_photo
    get_contestant
    if params[:photo_id].present?
      photo = @contestant.photos.find_by(id: params[:photo_id])
      if photo.present?
        photo.destroy
        msg = "You have deleted a photo."
      else
        msg = "Invalid photo, please try again later"
      end
    end
    redirect_to :back, alert: msg
  end

  private

  def get_pageant
    if current_user.vip? || current_user.admin?
      @pageant = Pageant.find_by(id: params[:pageant_id])
    else
      @pageant = current_user.pageants.not_deleted.find_by(id: params[:pageant_id])
    end

    if @pageant.nil?
      flash[:error] = "Pageant not found!"
      redirect_to current_pageants_path and return
    end
  end

  def get_pageant_public_access
    @pageant = Pageant.not_deleted.find_by(id: params[:pageant_id]) # Allow everyone to vote

    if @pageant.nil?
      flash[:error] = "Pageant not found!"
      redirect_to current_pageants_path and return
    elsif !@pageant.published? && (!user_signed_in? || !@pageant.authorized?(current_user))
      redirect_to current_pageants_path and return
    end
    
    get_contestant
  end

  def get_contestant
    if @pageant.present?
      @contestant = @pageant.contestants.not_deleted.find_by(id: params[:id])

      if @contestant.nil?
        flash[:error] = "Contestant not found!"
        redirect_to pageant_path(@pageant) and return
      end
    end
  end

  def contestant_params
    params.require(:contestant).permit(:number, :name, :description, :gender, :vote_count)
  end

  def contestant_photos_params
    params.require(:contestant).permit(:id, photos_attributes: [:image])
  end
end

app/helpers/contestants_helper.rb
module ContestantsHelper
end

app/views/contestants/_contestant.html.haml
- pageant = contestant.pageant
.contestant{id: "contestant_#{contestant.id}"}
  .photo
    = link_to pageant_contestant_path(pageant, contestant), data: {no_turbolink: true} do
      - if contestant.photo.present?
        = image_tag contestant.photo.url(:small)
      - else
        - if pageant.male_only?
          = image_tag "contestant_male_sm.jpg"
        - elsif pageant.female_only?
          = image_tag "contestant_female_sm.jpg"
        - else
          = image_tag "contestant_#{contestant.gender}_sm.jpg"
  .info
    .number= "##{contestant.number}"
    .name
      = link_to contestant.name, pageant_contestant_path(contestant.pageant, contestant), data: {no_turbolink: true}
    .description= contestant.description
    - if contestant.pageant.show_votes?
      .votes
        - if contestant.pageant.done? && contestant.vote_count.present?
          = pluralize(contestant.vote_count, "vote")
        - else
          = pluralize(contestant.votes_count, "vote")

app/views/contestants/_contestants.html.haml
.row-fluid
  - if pageant.male_and_female?
    .col-sm-6
      %h3.acenter= "Male"
      .row.clearfix
        - if contestants.male.present?
          - contestants.male.sort_by_number.each do |male_contestant|
            .col-sm-12.clearfix.add-bottom
              = render "contestants/contestant", contestant: male_contestant
        - else
          .col-sm-12
            .alert.alert-warning.acenter.add-top
              - if pageant.done?
                No male contestants.
              - else
                No male contestants yet.
                - if pageant.authorized?(current_user)
                  = link_to "Click here to create.", new_pageant_contestant_path(pageant, gender: "male"), class: "no-wrap"
    .col-sm-6
      %h3.acenter= "Female"
      .row.clearfix
        - if contestants.female.present?
          - contestants.female.sort_by_number.each do |female_contestant|
            .col-sm-12.clearfix.add-bottom
              = render "contestants/contestant", contestant: female_contestant
        - else
          .col-sm-12
            .alert.alert-warning.acenter.add-top
              - if pageant.done?
                No female contestants.
              - else
                No female contestants yet.
                - if pageant.authorized?(current_user)
                  = link_to "Click here to create.", new_pageant_contestant_path(pageant, gender: "female"), class: "no-wrap"
  - else
    - if contestants.present?
      - contestants.each do |contestant|
        .col-sm-6.col-md-6.clearfix.add-top-bottom
          = render "contestants/contestant", contestant: contestant
    - else
      .col-sm-12
        .alert.alert-warning.acenter.add-top
          - if pageant.done?
            No contestants.
          - else
            No contestants yet.
            - if pageant.authorized?(current_user)
              = link_to "Click here to create.", new_pageant_contestant_path(pageant), class: "no-wrap"

app/views/contestants/_form.html.haml
= f.error_notification
.row-fluid.form-fields.clearfix
  .col-sm-6.no-pad
    = f.input :number, as: :string, label: "Contestant Number", input_html: {maxlength: 3, class: "numeric"}
  - if f.object.pageant.done?
    .col-sm-6.no-pad
      = f.input :vote_count, as: :string, label: "Total Votes", input_html: {maxlength: 5, class: "numeric"}
  .col-sm-12.no-pad  
    = f.input :name, label: "Contestant Name", input_html: {maxlength: 27}
  .col-sm-12.no-pad  
    = f.input :description, label: "Contestant Description", input_html: {rows: 2, maxlength: 44}
  - if f.object.pageant.male_and_female?
    .col-sm-12.no-pad
      = f.input :gender, as: "radio_buttons", collection: Contestant.genders.collect{|k,v| [k.titleize,k]}, checked: params[:gender].present? ? params[:gender] : f.object.gender
  
.form-buttons
  %p
    - if f.object.new_record?
      = f.submit "Add", class: "button"
      = link_to "Cancel", f.object.pageant, class: "btn btn-cancel"
    - else
      = f.submit "Save Changes", class: "button"
      = link_to "Cancel", pageant_contestant_path(f.object.pageant, f.object), class: "btn btn-cancel"

app/views/contestants/_upload_modal.html.haml
#contestant_upload.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %h4= "Upload Photo"
      .modal-body
        .row
          = simple_form_for(@contestant, url: upload_process_pageant_contestant_path, method: :post, html: {class: "form", autocomplete: "off", multipart: true, id: "contestant_upload_form"}, data: {photo_limit: Photo::LIMIT, uploaded_count: @contestant.photos.count}) do |f|
            .form-error-message
              = f.error_notification
            = f.hidden_field :id
            .form-fields
              .form-group.file
                = file_field_tag "contestant[photos_attributes][][image]", multiple: true, class: "file form-control"
                %p.help-block= "For better display, upload image with 290 width x 400 height dimension"
      .modal-footer
        .pull-left
          .has-error
            %p.help-block
              - if @contestant.photos.present?
                - available = Photo::LIMIT - @contestant.photos.count
                = "You can upload #{available} more photo#{'s' if available > 1} for this contestant."
              - else
                = "You only allowed to upload up to #{Photo::LIMIT} photos."
        .btn{data: {dismiss:"modal"}}="Cancel"
        %button.btn.btn-default{disabled: true, data: {form_target: "contestant_upload_form"}}= "Upload"

app/views/contestants/edit.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      - if @pageant.header.present?
        .pageant-header
          = image_tag @pageant.header.url(:original)
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "Pageant Info", @pageant
          %li>
            = link_to "Edit Contestant", new_pageant_contestant_path(@pageant), class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            = simple_form_for(@contestant, url: pageant_contestant_path(@pageant, @contestant), html: {class: "form", autocomplete: "off"}) do |f|
              = render "contestants/form", f: f
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/contestants/new.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      - if @pageant.header.present?
        .pageant-header
          = image_tag @pageant.header.url(:original)
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "Pageant Info", @pageant
          %li>
            = link_to "Add Contestant", new_pageant_contestant_path(@pageant), class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            = simple_form_for(@contestant, url: pageant_contestants_path, html: {class: "form", autocomplete: "off"}) do |f|
              = render "contestants/form", f: f
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/contestants/show.html.haml
- content_for :title, "#{@contestant.name} - #{@pageant.name} - #{ENV['APP_NAME']}"
- content_for :info_url, pageant_contestant_url(@pageant, @contestant)
- content_for :info_title, "Vote #{@contestant.name}"
- content_for :info_description, @contestant.description.present? ? @contestant.description : @pageant.name
- content_for :info_image, @contestant.photos.present? ? asset_url(@contestant.photos.first.image.url(:medium)) : "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      - if @pageant.header.present?
        .pageant-header
          = image_tag @pageant.header.url(:original)
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to @pageant do
              = "Pageant Info"
          %li>
            = link_to "View Contestant", pageant_contestant_path(@pageant, @contestant), class: "active"
          - if @pageant.authorized?(current_user)
            %li>
              = link_to "Add Contestant", new_pageant_contestant_path(@pageant, gender: @contestant.gender)
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            .info-container.clearfix
              .row
                .col-sm-4
                  .gallery-container.pull-left
                    .main-image-container
                      - if @contestant.photos.present?
                        .main-image-slider
                          - @contestant.photos.each_with_index do |photo, index|
                            .main-image{class: "#{'admin' if @pageant.authorized?(current_user)}"}
                              .image
                                = image_tag photo.image.url(:regular), class: "gallery-image", data: {image_thumb: photo.image.url(:small)}
                              .action
                                = link_to delete_photo_pageant_contestant_path(@pageant, @contestant, photo_id: photo.id), method: :post, data: {confirm: "Are you sure you want to delete this photo?"}, class: "delete_photo" do
                                  = fa_icon"remove"
                      - else
                        - if @pageant.male_only?
                          = image_tag "contestant_male.jpg", class: "hidden-xs"
                        - elsif @pageant.female_only?
                          = image_tag "contestant_female.jpg", class: "hidden-xs"
                        - else
                          = image_tag "contestant_#{@contestant.gender}.jpg", class: "hidden-xs"

                .col-sm-8
                  .boost-votes-details.pull-left
                    %div= "CONTESTANT ##{@contestant.number}"
                    .page-title= @contestant.name
                    .boost-votes-title= "Boost Votes"
                    = form_for :boost_votes, url: boost_vote_pageant_contestant_path(@pageant, @contestant) do |f|
                      %p
                        - @boost_votes.each_with_index do |boost_vote, index|
                          .boost-votes-option
                            = radio_button_tag 'boost_vote', boost_vote.code, index == 0, class: "boost_vote_radio"
                            = image_tag "BoostVotes-#{boost_vote.name.split('-').last.strip.titleize}.png"
                            = boost_vote.description
                      = f.submit "Boost Vote", class: "btn btn-lg btn-success submit-boost-votes-button"
                    .cancel-boost-votes
                      = link_to "Cancel", "#", class: "cancel-boost-votes-button"
                  .info-details.pull-left
                    %div= "CONTESTANT ##{@contestant.number}"
                    .page-title= @contestant.name
                    - if @pageant.authorized?(current_user)
                      .page-controls
                        = link_to edit_pageant_contestant_path(@pageant, @contestant) do
                          = fa_icon("pencil")
                          = "Edit"
                        - if @contestant.photos.count < Photo::LIMIT
                          = link_to "#", id: "contestant_upload_modal_button", data: {modal_target: "#contestant_upload"} do
                            = fa_icon("photo")
                            = "Upload Photo"
                        = link_to pageant_contestant_path(@pageant, @contestant), method: :delete, data: {confirm: "Are you sure you want to delete this contestant?", confirm_subtitle: "Warning! You cannot undo this action."} do
                          = fa_icon("remove")
                          = "Delete"
                    .page-info
                      - if @contestant.description.present?
                        .page-description= @contestant.description
                      - if @contestant.pageant.show_votes?
                        .page-votes
                          - if @pageant.done? && @contestant.vote_count.present?
                            = pluralize(@contestant.vote_count, "vote")
                          - else
                            = pluralize(@contestant.votes_count, "vote")
                            - if admin?
                              .page-votes-link
                                = link_to votes_pageant_contestant_path(@pageant, @contestant) do
                                  = fa_icon("info")
                                  = "View Vote Details"
                      - if @contestant.pageant.upcoming?
                        .page-count-down
                          - if @seconds_remaining > 0
                            .count-down-title= "The voting will start in (#{ENV['TIMEZONE_CODE']}):"
                            .counter_table{data: {date: "#{@contestant.pageant.voting_start}", remaining_seconds: @seconds_remaining}}
                              .item-group
                                .item
                                  .days 0
                                  .label Days
                                .item
                                  .hours 0
                                  .label Hours
                                .item
                                  .minutes 0
                                  .label Minutes
                                .item
                                  .seconds 0
                                  .label Seconds
                      - else
                        %div.mobile-center
                          - if @contestant.pageant.ongoing?
                            - vote_url = vote_pageant_contestant_path(@pageant, @contestant)
                            - if user_signed_in?
                              - if !current_user.blocked? && !blocked_ip?
                                = "You have #{@remaining_votes} remaining vote#{'s' if @remaining_votes > 1} for this pageant."
                                %br/
                                - if @remaining_votes > 0
                                  - vote_msg = params[:voted] == "true" ? "Vote Again" : "Vote"
                                  = link_to vote_msg, vote_url, class: "btn btn-lg btn-success vote-button"
                                  - if @contestant.pageant.boost_votes?
                                    .boost-votes
                                      = link_to "Give Your Contestant A Boost", "#", class: "btn boost-votes-button"
                                - else
                                  .alert.alert-warning.alert-large.alert-center.add-top-bottom
                                    =raw @contestant.vote_warning(current_user, true)
                            - else
                              = link_to "Vote", signin_path(next_url: vote_url), class: "btn btn-lg btn-info vote-button"
                              - if @contestant.pageant.boost_votes?
                                .boost-votes
                                  = link_to "Give Your Contestant A Boost", signin_path(next_url: pageant_contestant_url(@pageant, @contestant, go: "boost_votes")), class: "btn login-boost-votes-button"

                    = render "shared/social_share_buttons", term: "contestant"

                    - if @pageant.fb_button.present?
                      = render "pageants/fb_plugin", content: @pageant.fb_button, pageant_id: @pageant.id

          .row-fluid
            .col-sm-12
              %h3.title_main
          = render "contestants/contestants", pageant: @pageant, contestants: @contestants
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      - if @pageant.show_votes?
        - if @top_contestants.present?
          = render "pageants/side_list", pageant: @pageant, contestants: @top_contestants, title: "Top #{@contestant.gender.titleize} Contestants"
      - if @other_pageants.present?
        = render "pageants/other_pageants", pageants: @other_pageants, title: "Current Pageants"
      = render "shared/side_script"
= render "contestants/upload_modal"

app/views/contestants/votes.html.haml
- content_for :title, "#{@contestant.name} - #{@pageant.name} - #{ENV['APP_NAME']}"
- content_for :info_url, pageant_contestant_url(@pageant, @contestant)
- content_for :info_title, "Vote #{@contestant.name}"
- content_for :info_description, @contestant.description.present? ? @contestant.description : @pageant.name
- content_for :info_image, @contestant.photos.present? ? asset_url(@contestant.photos.first.image.url(:medium)) : "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      - if @pageant.header.present?
        .pageant-header
          = image_tag @pageant.header.url(:original)
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to @pageant do
              = "Pageant Info"
          %li>
            = link_to "View Contestant", pageant_contestant_path(@pageant, @contestant)
          %li>
            = link_to "Vote Details", votes_pageant_contestant_path(@pageant, @contestant), class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            .info-container.clearfix
              .row
                .col-sm-12
                  .info-details.acenter
                    .page-light-title= @pageant.name
                    .page-small-title= "CONTESTANT ##{@contestant.number}"
                    .page-title= @contestant.name
          .row-fluid.clearfix
            .col-sm-12
              - if @votes.present?
                %table.table.table-striped.table-bordered
                  %tr
                    %th= "Voter"
                    %th.acenter= "IP Address"
                    %th.acenter= "Date"
                  - @votes.each do |vote|
                    %tr
                      %td
                        .pull-right.label.label-default= vote.user.role.upcase
                        = link_to vote.user.name, user_path(vote.user)
                        - if vote.quantity > 1
                          = "(#{vote.quantity} votes)"
                      %td.acenter= vote.ip_address
                      %td.acenter= wiser_date vote.created_at, real_time: false
                .row-fluid.acenter
                  .span12= paginate @votes
              - else
                .alert.alert-warning.acenter
                  No votes yet.

    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      - if @top_contestants.present?
        = render "pageants/side_list", pageant: @pageant, contestants: @top_contestants, title: "Top #{@contestant.gender.titleize} Contestants"
      - if @other_pageants.present?
        = render "pageants/other_pageants", pageants: @other_pageants, title: "Current Pageants"
      = render "shared/side_script"
= render "contestants/upload_modal"