config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#home'

  get '/error' => 'visitors#error', as: 'error'
  get '/whatsmyip' => 'visitors#ip_address', as: 'ip_address'
  get '/visitor/signin' => 'visitors#signin', as: :signin_page
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/error' => 'visitors#error'
  get '/home' => 'visitors#index', as: "home"
  get '/auth/failure' => 'sessions#failure'

  get "/paypal_success" => "users#paypal_success", as: "paypal_success"
  get "/paypal_failed" => "users#paypal_failed", as: "paypal_failed"

  post '/users/me' => 'users#show'

  get "/current" => "pageants#current", as: "current_pageants"
  get "/past" => "pageants#past", as: "past_pageants"
  get "/all" => "pageants#all", as: "all_pageants"
  get "/pageants/current" => redirect("/current")
  get "/pageants/past" => redirect("/past")
  get "/pageants/all" => redirect("/all")

  resources :users, except: [:new, :delete] do
    collection do
      post :go_premium
      post :buy_votes
    end
    member do
      get :account
      get :register_premium
      post :block
      post :unblock
      post :withdraw
      post :give_bonus
    end
  end

  resources :withdrawals, only: [:index] do
    collection do
      post :complete
      post :reject
    end
    member do
      post :approve
    end
  end

  resources :settings, only: [] do
    collection do
      get :edit
      post :update
    end
  end

  resources :transactions, only: [:create]

  get '/info/:id' => 'contents#show', as: :info
  resources :contents, only: [:index, :show, :edit, :update] do
    collection do
      post :upload_image
    end
  end

  resources :pageants do
    member do
      post :publish
      post :unpublish
    end
    resources :contestants, except: [:index] do
      member do
        post :boost_vote
        get :vote
        get :votes
        get :upload
        post :upload_process
        post :delete_photo
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  paginates_per 100

  enum gender: [:female, :male]
  enum role: [:user, :vip, :admin]

  after_create :record_activity

  after_initialize :set_default_role, :if => :new_record?

  has_many :authentications, dependent: :destroy
  has_many :pageants
  has_many :bulk_votes, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :premium_transactions, dependent: :destroy
  has_many :activities, dependent: :destroy
  has_many :withdrawals
  has_many :bonus, class_name: "Bonus"
  has_one :wallet

  scope :premium, -> { where("premium_until IS NOT NULL", Date.today) }
  scope :with_email, -> { where("email IS NOT NULL", Date.today) }
  scope :with_pageants, -> { where("pageants_count > 0") }
  scope :with_votes, -> { where("votes_count > 0") }

  def give_bonus(amount)
    return false unless Withdrawal.valid_amount?(amount)
    prepare_wallet

  end

  def total_profit
    profit = 0.00
    pageants.each do |pageant|
      profit += pageant.profit
    end
    profit
  end

  def unpaid_pageant_ids
    Contestant.active.where("contestants.pageant_id IN (?) AND contestants.vote_count IS NOT NULL", pageants.pluck(:id)).pluck(:pageant_id).uniq
  end

  def can_withdraw?
    !withdrawals.where(status: Withdrawal.statuses["pending"]).present?
  end

  def prepare_wallet
    self.build_wallet.save unless self.wallet.present?
  end

  def current_balance
    wallet.present? ? wallet.amount : 0
  end

  def total_withdrawal
    withdrawals.completed.sum(:amount)
  end

  def set_default_role
    if User.count == 0
      self.role ||= :admin
    else
      self.role ||= :user
    end
  end

  def fb_photo_url
    auth = authentications.where(provider: "facebook").first
    auth.present? && auth.uid.present? ? "http://graph.facebook.com/#{auth.uid}/picture?type=large" : nil
  end

  def fb_url
    auth = authentications.where(provider: "facebook").first
    auth.present? && auth.uid.present? ? "https://www.facebook.com/#{auth.uid}" : nil
  end

  def age
    now = Time.now.utc.to_date
    now.year - birth_date.year - (birth_date.to_date.change(:year => now.year) > now ? 1 : 0)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      if auth['uid'].present?
        authentication = Authentication.new(provider: auth['provider'], uid: auth['uid'])
        if authentication.save
          if auth['info']['email'].present?
            user = User.find_by(email: auth['info']['email'])
          else
            user = nil
          end
          user ||= User.new(auth: auth)
          user.email = auth['info']['email']
          user.first_name = auth['info']['first_name']
          user.last_name = auth['info']['last_name']
          if user.save
            authentication.update_attributes(user_id: user.id)
          else
            raise "Omniauth Error: User cannot be saved!"
          end
        else
          raise "Omniauth Error: Authentication cannot be saved!"
        end
      end
      return authentication
    end
  end

  def update_from_facebook(auth)
    info = auth['info']
    raw = auth['extra']['raw_info']
    self.auth = auth
    self.email = auth['info']['email']
    if info['location'].present?
      self.location = info['location']
    end
    if raw['name'].present?
      self.name = raw['name']
    end
    if raw['first_name'].present?
      self.first_name = raw['first_name']
    end
    if raw['last_name'].present?
      self.last_name = raw['last_name']
    end
    if raw['gender'].present?
      self.gender = raw['gender']
    end
    if raw['birthday'].present?
      self.birth_date = raw['birthday']
    end
    if raw['link'].present?
      self.url = raw['link']
    end
    self.save
  end

  def update_token(auth)
    credentials = auth['credentials']
    self.token = credentials['token']
    self.token_expires_at = Time.at(credentials['expires_at'])
    self.save
  end

  def name
    [first_name, last_name].join(" ").strip
  end

  def premium?
    return false unless premium_until.present?
    Date.today <= premium_until
  end

  def valid_token?
    return false unless token_expires_at.present?
    Time.now <= token_expires_at
  end

  def vote_per_hour
    premium? ? 5 : 1
  end

  def vote_per_day
    premium? ? 5 : 1
  end

  def record_activity
    Activity.create(user: self, resource: self, created_at: created_at, updated_at: updated_at, action: 'created')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_filter :authenticate_user!, except: [:go_premium]
  before_filter :authenticate_admin!, except: [:show, :account, :edit, :update, :go_premium, :paypal_success, :paypal_failed, :buy_votes]
  before_filter :get_user, except: [:go_premium, :index, :paypal_success, :paypal_failed, :buy_votes]

  def index
    if params[:q].present? && params[:q][:first_name_or_last_name_or_email_or_location_cont].present?
      @keyword = params[:q][:first_name_or_last_name_or_email_or_location_cont].downcase
    end
    @remove_keyword = true
    if @keyword == "admin"
      @users = User.admin
    elsif @keyword == "user"
      @users = User.user
    elsif @keyword == "premium"
      @users = User.premium
    elsif @keyword == "email"
      @users = User.with_email
    elsif @keyword == "votes"
      @users = User.with_votes
    elsif @keyword == "pageants"
      @users = User.with_pageants
    else
      @users = User.all
      @remove_keyword = false
    end

    if @remove_keyword && @keyword.present?
      params[:q][:first_name_or_last_name_or_email_or_location_cont] = ""
      @q = @users.search(params[:q])
      params[:q][:first_name_or_last_name_or_email_or_location_cont] = @keyword
    else
      @q = @users.search(params[:q])
    end
    @users = @q.result(distinct: true).page(params[:page]).includes(:wallet)
  end

  def show
    @activities = @user.activities.order("activities.created_at DESC").page(params[:page])
  end

  def account
    @pageants = @user.pageants.sort_start
    @withdrawals = @user.withdrawals
    @bonus = @user.bonus
  end

  def give_bonus
    @user.prepare_wallet
    if @user.wallet.add_bonus(params[:bonus][:amount], params[:bonus][:notes])
      redirect_to account_user_path(@user), notice: "You have added <b>#{number_to_currency(params[:bonus][:amount], unit: 'Php ')}</b> worth of bonus credits to #{@user.name}"
    else
      redirect_to :back, alert: "Failed to give bonus credits. Please try again."
    end
  end

  def edit
    redirect_to root_path if current_user.user? && current_user != @user
  end

  def block
    @user.update_attributes(blocked: true)
    redirect_to :back, notice: "You have blocked #{@user.name}."
  end

  def unblock
    @user.update_attributes(blocked: false)
    redirect_to :back, notice: "You have unblocked #{@user.name}."
  end

  def update
    redirect_to root_path if current_user.user? && current_user != @user
    if @user.update_attributes(user_params)
      if params[:id] == "me"
        if user_params[:paypal_email].present?
          redirect_to account_user_path("me"), notice: "You have saved your Paypal email."
        else
          redirect_to user_path("me"), notice: "You have saved your changes."
        end
      else
        if user_params[:paypal_email].present?
          redirect_to account_user_path(@user), notice: "You have saved the user's PayPal email."
        else
          redirect_to user_path(@user), notice: "You have saved your changes."
        end
      end
    else
      render :edit
    end
  end

  def register_premium
    @transaction = @user.premium_transactions.new
  end

  def go_premium
    unless current_user.present?
      redirect_to root_path, alert: "You should login to avail premium membership!"
    else
      premium = PremiumDenomination.find_by(code: params[:code])
      if premium.present?
        transaction = current_user.premium_transactions.create(premium_denomination: premium, price: premium.price)
        if transaction.setup!(paypal_success_url, paypal_failed_url)
          redirect_to transaction.redirect_uri
        else
          transaction.failed!
          redirect_to :back, alert: "Transaction failed. Please try again later."
        end
      else
        redirect_to :back
      end
    end
  end

  def withdraw
    amount = params[:withdrawal][:amount]
    if !@user.paypal_email.present?
      redirect_to account_user_path(@user), alert: "Sorry, you need to setup your Payment Settings to request for withdrawal."
    elsif !amount.present?
      redirect_to account_user_path(@user), alert: "Please entry the amount to request for withdrawal."
    elsif !Withdrawal.valid_amount?(amount)
      redirect_to account_user_path(@user), alert: "Sorry, \"<b>#{amount}</b>\" is an invalid withdrawal amount. Please try again."
    elsif amount.to_f > @user.current_balance
      redirect_to account_user_path(@user), alert: "Sorry, insufficient funds. You cannot withdraw <b>#{number_to_currency(amount, unit: 'Php ')}</b> because you only have <b>#{number_to_currency(@user.current_balance, unit: 'Php ')}</b> in your account."
    elsif amount.to_f < 100
      redirect_to account_user_path(@user), alert: "You cannot withdraw lower than Php 100.00, please try again later."
    elsif !@user.can_withdraw?
      redirect_to account_user_path(@user), alert: "You currently have a pending withdrawal request. Please wait until we process your request. Thank you!"
    else
      @withdrawal = @user.withdrawals.create(amount: amount)
      AdminMailer.new_withdrawal(@withdrawal).deliver!
      redirect_to account_user_path(@user), notice: "You have submitted your request to withdraw  <b>#{number_to_currency(amount, unit: 'Php ')}</b> from your account.<br/>Please wait until we completely process your previous request."
    end
  end

  def buy_votes
    redirect_to info_path("buy-a-vote") if params[:bulk_vote].present? && params[:bulk_vote][:quantity] == 0
    vote_denomination = PremiumDenomination.find_by(code: "PVP-BV")
    bulk_vote = current_user.bulk_votes.new(bulk_vote_params)
    transaction = current_user.premium_transactions.create(premium_denomination: vote_denomination, price: vote_denomination.price, quantity: bulk_vote.quantity)
    bulk_vote.premium_transaction = transaction
    if bulk_vote.save
      if transaction.setup!(paypal_success_url, paypal_failed_url)
        redirect_to transaction.redirect_uri
      else
        transaction.failed!
        redirect_to :back, alert: "Transaction failed. Please try again later."
      end
    else
      transaction.failed!
    end
  end

  def paypal_success
    transaction = PremiumTransaction.find_by(token: params[:token])
    if transaction.present?
      if transaction.complete!(params[:PayerID])
        if transaction.premium_denomination.boost_vote?
          redirect_to pageant_contestant_path(transaction.bulk_vote.pageant_id, transaction.bulk_vote.contestant_id), notice: "Payment completed! Your boost votes are now counted."
        else
          redirect_to user_path("me"), notice: "Payment completed! You're now a premium user."
        end
      else
        if transaction.premium_denomination.boost_vote?
          redirect_to pageant_contestant_path(transaction.bulk_vote.pageant_id, transaction.bulk_vote.contestant_id), alert: "Payment failed! Please try again."
        else
          redirect_to user_path("me"), alert: "Payment failed! Please try again."
        end
      end
    else
      if transaction.premium_denomination.boost_vote?
        redirect_to pageant_contestant_path(transaction.bulk_vote.pageant_id, transaction.bulk_vote.contestant_id), alert: "Payment failed! Please contact our support for assistance."
      else
        redirect_to user_path("me"), alert: "Payment failed! Please contact our support for assistance."
      end
      redirect_to user_path("me"), alert: "Payment failed! Please contact our support for assistance."
    end
  end

  def paypal_failed
    transaction = PremiumTransaction.find_by(token: params[:token])
    if transaction.present?
      transaction.update_attributes(completed_at: Time.now)
      transaction.failed!
      if transaction.premium_denomination.boost_vote?
        redirect_to pageant_contestant_path(transaction.bulk_vote.pageant_id, transaction.bulk_vote.contestant_id), alert: "Payment failed! Please try again."
      else
        redirect_to user_path("me"), alert: "Payment failed! Please try again."
      end
    else
      redirect_to root_path, alert: "Payment failed! Please try again."
    end
    
  end

  private

  def get_user
    redirect_to root_path and return if params[:id] == "go_premium"
    redirect_to root_path and return if params[:id] != "me" && !admin?
    @user = params[:id] == "me" ? current_user : User.find(params[:id])
  end

  def bulk_vote_params
    params.require(:bulk_vote).permit(:pageant_id, :contestant_id, :quantity)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :gender, :birth_date, :location, :role, :paypal_email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= f.error_notification
.row-fluid.form-fields.clearfix
  - if f.object.email.present?
    .col-sm-12.no-pad
      = f.input :email, readonly: true
  .col-sm-6.no-pad
    = f.input :first_name
  .col-sm-6.no-pad
    = f.input :last_name
  .col-sm-6.no-pad
    = f.input :location
  .col-sm-6.no-pad
    = f.input :birth_date, as: "string", input_html: {class: "date-basic"}
  .col-sm-6.no-pad
    = f.input :gender, as: "radio_buttons", collection: User.genders.collect{|k,v| [k.titleize,k]}, checked: f.object.gender
  - if admin? && current_user != f.object
    .col-sm-6.no-pad
      = f.input :role, as: "radio_buttons", collection: User.roles.collect{|k,v| [k.titleize,k]}, checked: f.object.role
  
.form-buttons
  %p
    = f.submit "Save Changes", class: "button"
    = link_to "Cancel", user_path(params[:id]), class: "btn btn-cancel"

app/views/users/_withdrawal_modal.html.haml
#request_withdrawal.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %h4= "Withdraw"
      .modal-body
        .row
          .col-sm-12.acenter
            = simple_form_for Withdrawal.new, url: withdraw_user_path(@user), html: {method: :post, class: "form", autocomplete: "off"} do |f|
              %h4= "Enter the desired amount to withdraw:"
              = f.input :amount, wrapper: "append", label: false, required: false, class: "input-lg", hint: "You can only withdraw Php 100.00 or greater." do
                %span.input-group-addon= "Php"
                = f.input_field :amount, as: "string"
      .modal-footer
        .btn{data: {dismiss:"modal"}}
          = "Cancel"
        %button.btn.btn-default{data: {form_target: "#new_withdrawal"}}
          = "Request"

app/views/users/edit.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            - if params[:id] == "me"
              = link_to "Profile", user_path("me")
            - else
              = link_to "User List", users_path
          %li>
            - if params[:id] == "me"
              = link_to "Edit Profile", edit_user_path("me"), class: "active"
            - else
              = link_to "Edit User", edit_user_path(@user), class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-8
            = simple_form_for(@user, url: user_path(params[:id]), html: {class: "form", autocomplete: "off"}) do |f|
              = render "users/form", f: f
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/users/index.html.haml
.container-fluid.clearfix
  .row-fluid.add-top
    .col-sm-12
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "Users List", users_path, class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .search-list
            = search_form_for @q, url: users_path do |f|
              .input-group.input-group-sm.short-search
                = f.text_field :first_name_or_last_name_or_email_or_location_cont, placeholder: "Search User", value: @keyword
                .input-group-btn
                  = f.button fa_icon("search"), class: "btn"
          .row-fluid.clearfix
            .col-sm-12
          .row-fluid.clearfix
            .col-sm-12
              - if @users.present?
                .pagination_info= page_entries_info @users
                %table.table.table-striped.table-bordered.table-slim
                  %tr
                    %th
                      = sort_link @q, :first_name, "Name"
                    %th.hidden-xs.hidden-sm
                      = sort_link @q, :email
                    %th.hidden-xs.hidden-sm.acenter
                      = sort_link @q, :location
                    %th.hidden-xs.hidden-sm.acenter
                      = sort_link @q, :wallet_amount, "Wallet"
                    %th.hidden-xs.hidden-sm.acenter
                      = sort_link @q, :votes_count, "Votes"
                    %th.hidden-xs.hidden-sm.acenter
                      = sort_link @q, :pageants_count, "Pageants"
                    %th.hidden-xs.acenter
                      = sort_link @q, :premium_until
                  - @users.each do |user|
                    %tr
                      %td
                        .btn-group
                          .btn.btn-xs.dropdown-toggle{data: {toggle: "dropdown"}}
                            = fa_icon "cog"
                          %ul.dropdown-menu{role: "menu"}
                            %li
                              = link_to user_path(user) do
                                = fa_icon "eye", class: "link-icon"
                                = "View Activities"
                            %li
                              = link_to edit_user_path(user) do
                                = fa_icon "pencil", class: "link-icon"
                                = "Edit User"
                            - if user.url.present?
                              %li
                                = link_to user.url, target: "_blank" do
                                  = fa_icon "facebook", class: "link-icon"
                                  = "Visit FB Profile"
                            - if !user.premium?
                              %li
                                = link_to register_premium_user_path(user) do
                                  = fa_icon "star", class: "link-icon"
                                  = "Set as Premium User"
                            %li
                              - if user.blocked?
                                = link_to unblock_user_path(user.id), method: "post", data: {confirm: "Are you sure you want to unblock #{user.name}?<br/><small>The user can cast votes again when unblocked.</small>",}, class: "link-green" do
                                  = fa_icon "check", class: "link-icon"
                                  = "Unblock"
                              - else
                                = link_to block_user_path(user.id), method: "post", data: {confirm: "Are you sure you want to block #{user.name}?<br/><small>The user can no longer cast votes when blocked.</small>",}, class: "link-red" do
                                  = fa_icon "remove", class: "link-icon"
                                  = "Block"
                        = link_to highlight(user.name, @keyword), user_path(user)
                        - if user.blocked?
                          .label.label-danger.pull-right= "Blocked"
                        - else
                          .label.label-default.pull-right= user.role.upcase
                      %td.hidden-xs.hidden-sm
                        =raw user.email.present? ? highlight(user.email, @keyword) : "-"
                      %td.hidden-xs.hidden-sm.acenter
                        =raw user.location.present? ? highlight(user.location, @keyword) : "-"
                      %td.hidden-xs.hidden-sm.aright.w100
                        .pull-left= "Php"
                        = number_to_currency(user.wallet.present? ? user.wallet.amount : 0, unit: "")
                      %td.hidden-xs.hidden-sm.acenter
                        = user.votes_count
                      %td.hidden-xs.hidden-sm.acenter
                        = user.pageants_count
                      %td.hidden-xs.acenter
                        =raw highlight("#{format_date(user.premium_until)}", @keyword)
                        - if user.premium_until.present?
                          - if !user.premium?
                            .pull-right= fa_icon "warning"
                          - else
                            .pull-right= fa_icon "check"
                        - else
                          = fa_icon "remove"
                .row-fluid.clearfix
                  .col-sm-12.acenter= paginate @users
                  .pagination_info= page_entries_info @users
              - else
                .row-fluid.clearfix
                  .col-sm-12
                    .alert.alert-warning.acenter
                      No results found.
                      = link_to "Click here", users_path
                      to clear your search.

app/views/users/register_premium.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            - if params[:id] == "me"
              = link_to "Profile", user_path("me"), class: "active"
            - else
              = link_to "User List", users_path
          %li>
            - if params[:id] == "me"
              = link_to "Edit Profile", edit_user_path("me")
            - else
              = link_to "View User", user_path(@user), class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            .info-container.clearfix
              .row-fluid
                - if @user.fb_photo_url.present?
                  .col-sm-4
                    .gallery-container.pull-left
                      .main-image-container
                        = image_tag @user.fb_photo_url, class: "gallery-image"
                %div{class: "#{@user.fb_photo_url.present? ? 'col-sm-8' : 'col-sm-12'}"}
                  .info-details.pull-left
                    - if admin?
                      .page-intro
                        .label.label-default= @user.role.upcase
                        .label.label-default= @user.premium? ? "Premium User" : "Free User"
                    .page-title= @user.name
                    .page-description
                      = "Registered since: #{format_date(@user.created_at)}"
                      %br/
                      - if @user.premium?
                        = "Premium until: #{format_date(@user.premium_until)}"
                        %br/
                      = @user.email
                      - if @user.location.present?
                        %br/
                        = @user.location
                      - if @user.birth_date.present?
                        %br/
                        = pluralize(@user.age, "year")
                        = "old"
              .row-fluid
                .col-sm-12
                  %h3.title_main
              .row-fluid
                .col-sm-12
                  %h3.title_main.no-line= "Register as Premium Member"
              .row-fluid
                .col-sm-12
                  - if !@user.premium?
                    .row-fluid.pad-top-bottom-medium.clearfix
                      .col-sm-12
                        = simple_form_for(@transaction, url: transactions_path(user_id: @user.id), html: {class: "form", autocomplete: "off"}) do |f|
                          = render "transactions/form", f: f
                  - else
                    .row-fluid.clearfix
                      .col-sm-12
                        .alert.alert-warning.acenter
                          User is already a premium member.
                          = link_to "Click here", @user
                          to go back.

    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/users/show.html.haml
= render "withdrawals/bonus_modal"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          - if params[:id] == "me"
            %li>
              = link_to "Profile", user_path("me"), class: "active"
            %li>
              = link_to "Account", account_user_path("me")
          - else
            %li>
              = link_to "User List", users_path
            %li>
              = link_to "User Activities", user_path(@user), class: "active"
            %li>
              = link_to "User Account", account_user_path(@user)
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            .info-container.clearfix
              .row-fluid
                - if @user.fb_photo_url.present?
                  .col-sm-4
                    .gallery-container.pull-left
                      .main-image-container
                        = image_tag @user.fb_photo_url, class: "gallery-image"
                %div{class: "#{@user.fb_photo_url.present? ? 'col-sm-8' : 'col-sm-12'}"}
                  .info-details.pull-left
                    - if admin?
                      .page-intro
                        .label.label-default= @user.role.titleize
                        .label.label-default= @user.premium? ? "Premium User" : "Free User"
                        - if @user.blocked?
                          .label.label-danger= "Blocked"
                    .page-title
                      = @user.name
                    - if params[:id] != "me" && admin?
                      .page-controls
                        = link_to edit_user_path(params[:id]) do
                          = fa_icon("pencil")
                          = "Edit User"
                        - if @user.fb_url.present?
                          = link_to @user.fb_url, target: "_blank" do
                            = fa_icon("user")
                            = "View on Facebook"
                        - if !@user.premium?
                          %br/
                          = link_to register_premium_user_path(params[:id]) do
                            = fa_icon("star")
                            = "Set as Premium User"
                        = link_to "#", class: "no-link", data: {modal_target: "#give_bonus"} do
                          = fa_icon("money")
                          = "Send Credits"

                        - if @user.blocked?
                          = link_to unblock_user_path(params[:id]), method: "post", data: {confirm: "Are you sure you want to unblock #{@user.name}?<br/><small>The user can cast votes again when unblocked.</small>",}, class: "link-green" do
                            = fa_icon("check")
                            = "Unblock"
                        - else
                          = link_to block_user_path(params[:id]), method: "post", data: {confirm: "Are you sure you want to block #{@user.name}?<br/><small>The user can no longer cast votes when blocked.</small>",}, class: "link-red" do
                            = fa_icon("remove")
                            = "Block"

                    .page-description
                      - if @user.premium?
                        = "Premium until: #{format_date(@user.premium_until)}"
                        %br/
                      = @user.email
                      - if @user.location.present?
                        %br/
                        = @user.location
                      - if @user.birth_date.present?
                        %br/
                        = pluralize(@user.age, "year")
                        = "old"
                    %div.mobile-center
                      - if current_user == @user && params[:id] == "me" && !@user.premium?
                        = link_to "Be a premium user", info_path("premium-membership"), class: "btn btn-lg btn-success premium-button"
              .row-fluid
                .col-sm-12
                  %h3.title_main
              .row-fluid
                .col-sm-12
                  %h3.title_main.no-line= "User Activities"
              .row-fluid
                .col-sm-12
                  - if @activities.present?
                    %table.table.table-bordered.table-striped
                      - @activities.each do |activity|
                        - if activity.resource.present?
                          = render "activities/#{activity.resource_type.underscore}", activity: activity
                  - else
                    .row-fluid.clearfix
                      .col-sm-12
                        .alert.alert-warning.acenter
                          No activities yet.
              .row-fluid.clearfix
                .col-sm-12.acenter= paginate @activities
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"