config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#home'

  get '/error' => 'visitors#error', as: 'error'
  get '/whatsmyip' => 'visitors#ip_address', as: 'ip_address'
  get '/visitor/signin' => 'visitors#signin', as: :signin_page
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/error' => 'visitors#error'
  get '/home' => 'visitors#index', as: "home"
  get '/auth/failure' => 'sessions#failure'

  get "/paypal_success" => "users#paypal_success", as: "paypal_success"
  get "/paypal_failed" => "users#paypal_failed", as: "paypal_failed"

  post '/users/me' => 'users#show'

  get "/current" => "pageants#current", as: "current_pageants"
  get "/past" => "pageants#past", as: "past_pageants"
  get "/all" => "pageants#all", as: "all_pageants"
  get "/pageants/current" => redirect("/current")
  get "/pageants/past" => redirect("/past")
  get "/pageants/all" => redirect("/all")

  resources :users, except: [:new, :delete] do
    collection do
      post :go_premium
      post :buy_votes
    end
    member do
      get :account
      get :register_premium
      post :block
      post :unblock
      post :withdraw
      post :give_bonus
    end
  end

  resources :withdrawals, only: [:index] do
    collection do
      post :complete
      post :reject
    end
    member do
      post :approve
    end
  end

  resources :settings, only: [] do
    collection do
      get :edit
      post :update
    end
  end

  resources :transactions, only: [:create]

  get '/info/:id' => 'contents#show', as: :info
  resources :contents, only: [:index, :show, :edit, :update] do
    collection do
      post :upload_image
    end
  end

  resources :pageants do
    member do
      post :publish
      post :unpublish
    end
    resources :contestants, except: [:index] do
      member do
        post :boost_vote
        get :vote
        get :votes
        get :upload
        post :upload_process
        post :delete_photo
      end
    end
  end
end

app/views/shared/_analytics.html.haml
- case ENV['DOMAIN_NAME']
- when 'pageantvote.net'
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-34616431-1', 'auto');
    ga('send', 'pageview');
- when 'pageantvote.ph'
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-34616431-3', 'auto');
    ga('send', 'pageview');
- when 'pageantvote.co.za'
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-34616431-4', 'auto');
    ga('send', 'pageview');
- when 'pageantvote.co'
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-34616431-5', 'auto');
    ga('send', 'pageview');
- when 'pageantvote.online'
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-34616431-6', 'auto');
    ga('send', 'pageview');

app/views/shared/_footer.html.haml
.footer.add-top-large
  .container.copyright
    .row
      .col-sm-8.col-md-8.mobile-center
        - Content.enabled.each do |content|
          - next if Content::NO_PREVIEW.include?(content.area)
          - if content.area == "buy-a-vote"
            - if user_signed_in?
              = link_to content.title, info_path(content.area)
          - else
            = link_to content.title, info_path(content.area)
      .col-sm-4.col-md-4.aright.mobile-center
        %span.no-wrap.add-left-right= "#{ENV['APP_NAME']} Copyright © #{Date.today.year} [#{ENV['TIMEZONE_CODE']}]"
        / %span.no-wrap.add-left-right.developer
        /   Developed by
        /   = link_to "Bud Brothers", "http://budbrosdev.com", target: "_blank"

app/views/shared/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: 'navbar-brand' do
        = image_tag("logo.png")
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'shared/navigation_links'

app/views/shared/_navigation_links.html.haml
%li
  = link_to "Home", home_path
%li
  = link_to "Pageants", current_pageants_path

- if user_signed_in?
  %li
    = link_to "My Pageants", pageants_path
  %li
    - if content = Content.find_by_area_and_status("create-a-pageant", 1)
      = link_to content.title, info_path(content.area)
    - else
      = link_to "Create a Pageant", new_pageant_path
  %li
    = link_to "Profile", user_path("me")
- else
  - if content = Content.find_by_area_and_status("create-a-pageant", 1)
    %li
      = link_to content.title, info_path(content.area)
- if admin?
  %li
    = link_to "Users", users_path
  %li
    = link_to "Content", contents_path
  %li
    = link_to withdrawals_path do
      - pending = Withdrawal.pending.count(:id)
      - if pending > 0
        = "Withdrawals (#{pending})"
      - else
        = "Withdrawals"
  %li
    = link_to "Settings", edit_settings_path

%li
  - if user_signed_in?
    = link_to 'Logout', signout_path, data: {confirm: "Do you want to logout your #{ENV['APP_NAME']} account?", confirm_subtitle: "Warning! This will not signout your Facebook account.<br/>Visit <a href='https://facebook.com' target='_blank'>Facebook</a> to logout your account manually."}
  - else
    = link_to 'Login via Facebook', signin_path

app/views/shared/_responsive_ad.html.haml
.ad-box
  %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
  / Large Going Down
  %ins.adsbygoogle{"data-ad-client" => "ca-pub-5930036773855425", "data-ad-slot" => "5185996598", :style => "display:inline-block;width:300px;height:600px"}
  :javascript
    (adsbygoogle = window.adsbygoogle || []).push({});

app/views/shared/_responsive_ad2.html.haml
.ad-box
  #switch_placeholder_1232b83285f07df4fc625e59d810cd0a.switch_placeholder
  :javascript
    (__scads = window.__scads || []).push({"z":28791,"targetId":"switch_placeholder_1232b83285f07df4fc625e59d810cd0a","domain":"delivery.myswitchads.com","width":"300","height":"250"});
  %script{:async => "", :src => "//delivery.myswitchads.com/adserver/sat.js?v=2"}

app/views/shared/_side_images.html.haml
- content = Content.find_by(area: "side-images")
- if content.enabled? && content.script.present?
  .side-images
    .wysiwyg-content
      = raw(content.script)
- else
  - if admin?
    .side-images
      .alert.alert-warning.acenter
        = link_to "Click here to update Side Images.", edit_content_path(content)

app/views/shared/_side_script.html.haml
- content = Content.find_by(area: "side-script")
- if content.enabled? && content.script.present?
  .ad-box
    = raw(content.script)
- else
  - if admin?
    .side-images
      .alert.alert-warning.acenter
        = link_to "Click here to update Side Script.", edit_content_path(content)

app/views/shared/_social.html.haml
.socialbar
  .container
    .row
      .span12.borderless.acenter.top-info
        = "You are currently logged in as #{current_user.name}."
        / %ul.ss.mobile-center
        /   %li.twitter
        /     %a{:href => "#"} twitter
        /   %li.facebook
        /     %a{:href => "#"} facebook
        /   %li.googleplus
        /     %a{:href => "#"} googleplus
        /   %li.dribbble
        /     %a{:href => "#"} dribbble
        /   %li.forrst
        /     %a{:href => "#"} forrst
        /   %li.rss
        /     %a{:href => "#"} rss

app/views/shared/_social_share_buttons.html.haml
.social-share-buttons-container
  .social-share-title= "Share this #{term} with: "
  - if !@pageant.present? && !@contestant.present?
    - title = "#{ENV['APP_NAME']}"
  = social_share_button_tag(yield(:info_title), "data-twitter-title" => "#{yield(:info_title)} @ #{ENV['APP_NAME']}", url: yield(:info_url), image: yield(:info_image), desc: yield(:info_description), popup: "true", rel: "pvshare", via: "PageantVoteOnline")