config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#home'

  get '/error' => 'visitors#error', as: 'error'
  get '/whatsmyip' => 'visitors#ip_address', as: 'ip_address'
  get '/visitor/signin' => 'visitors#signin', as: :signin_page
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/error' => 'visitors#error'
  get '/home' => 'visitors#index', as: "home"
  get '/auth/failure' => 'sessions#failure'

  get "/paypal_success" => "users#paypal_success", as: "paypal_success"
  get "/paypal_failed" => "users#paypal_failed", as: "paypal_failed"

  post '/users/me' => 'users#show'

  get "/current" => "pageants#current", as: "current_pageants"
  get "/past" => "pageants#past", as: "past_pageants"
  get "/all" => "pageants#all", as: "all_pageants"
  get "/pageants/current" => redirect("/current")
  get "/pageants/past" => redirect("/past")
  get "/pageants/all" => redirect("/all")

  resources :users, except: [:new, :delete] do
    collection do
      post :go_premium
      post :buy_votes
    end
    member do
      get :account
      get :register_premium
      post :block
      post :unblock
      post :withdraw
      post :give_bonus
    end
  end

  resources :withdrawals, only: [:index] do
    collection do
      post :complete
      post :reject
    end
    member do
      post :approve
    end
  end

  resources :settings, only: [] do
    collection do
      get :edit
      post :update
    end
  end

  resources :transactions, only: [:create]

  get '/info/:id' => 'contents#show', as: :info
  resources :contents, only: [:index, :show, :edit, :update] do
    collection do
      post :upload_image
    end
  end

  resources :pageants do
    member do
      post :publish
      post :unpublish
    end
    resources :contestants, except: [:index] do
      member do
        post :boost_vote
        get :vote
        get :votes
        get :upload
        post :upload_process
        post :delete_photo
      end
    end
  end
end

app/models/pageant.rb
class Pageant < ActiveRecord::Base
  paginates_per 20

  enum status: [:draft, :published, :unpublished, :deleted]
  enum category: [:male_and_female, :male_only, :female_only]

  after_create :record_activity

  has_attached_file :header, :styles => {cropped: "1000x300#"}
  has_attached_file :banner, :styles => {cropped: "690x315#"}
  has_attached_file :thumb, :styles => {cropped: "470x245#"}, default_url: "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
  validates_attachment_content_type :header, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :banner, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :thumb, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  counter_culture :user
  has_many :contestants, dependent: :destroy
  has_many :bulk_votes

  validates :name, :voting_start, :voting_end, :category, presence: true
  validate :voting_end_should_be_greater_than_voting_start

  scope :not_deleted, -> {where.not(status: Pageant.statuses[:deleted])}
  scope :current, -> {where("voting_end > ?", Time.now.utc)}
  scope :past, -> {where("voting_end <= ?", Time.now.utc)}
  scope :exclude_ids, ->(ids){where("id NOT IN (?)", ids)}
  scope :sort_start, ->{order("pageants.voting_start DESC")}

  def available_votes_of_user(user, gender)
    contestant_ids = male_and_female? ? contestants.send(gender).pluck(:id) : contestants.pluck(:id)
    date = Time.now.in_time_zone(ENV['TIMEZONE']).strftime("%Y-%m-%d")
    offset = Time.now.strftime("%z").gsub("0","").gsub("-", "- INTERVAL ").gsub("+", "+ INTERVAL ")
    vote_spent = user.votes.single.where("DATE(created_at #{offset} HOUR) = DATE(?) AND contestant_id IN (?)", date, contestant_ids).count
    user.vote_per_day - vote_spent
  end

  def profit
    regular_votes = votes.where(bought: false).count(:id)
    bulk_votes = votes.where(bought: true).count(:id)
    (regular_votes * Vote::REG_PRICE) + (bulk_votes * Vote::BLK_PRICE)
  end

  def votes
    Vote.where(contestant_id: contestants.pluck(:id))
  end

  def completed_bulk_votes
    bulk_votes.joins(:premium_transaction).where("premium_transactions.status = 1")
  end

  def voting_end_should_be_greater_than_voting_start
    if voting_start.present? && voting_end.present?
      if voting_start > voting_end
        errors.add(:voting_end, "should be greater than or equal to start date")
      end
    end
  end

  def authorized?(current_user = nil)
    return false unless current_user.present?
    current_user.admin? || current_user.vip? || current_user == self.user
  end

  def other(limit = 5)
    Pageant.published.not_deleted.where("voting_end > ? AND id <> ?", Time.now.utc, id).order("RAND()").limit(4)
  end

  def top(limit = 5, gender = nil)
    if gender.nil?
      results = contestants.not_deleted.joins(:votes).select("contestants.*, COUNT(votes.id) as vote_count").group("contestants.id").order("vote_count DESC").limit(limit)
      results = contestants.not_deleted.where("contestants.vote_count IS NOT NULL").order("contestants.vote_count DESC").limit(limit) unless results.present?
    elsif gender == "male"
      results = contestants.not_deleted.male.joins(:votes).select("contestants.*, COUNT(votes.id) as vote_count").group("contestants.id").order("vote_count DESC").limit(limit)
      results = contestants.not_deleted.male.where("contestants.vote_count IS NOT NULL").order("contestants.vote_count DESC").limit(limit) unless results.present?
    else
      results = contestants.not_deleted.female.joins(:votes).select("contestants.*, COUNT(votes.id) as vote_count").group("contestants.id").order("vote_count DESC").limit(limit)
      results = contestants.not_deleted.female.where("contestants.vote_count IS NOT NULL").order("contestants.vote_count DESC").limit(limit) unless results.present?
    end
    return results
  end

  def published_status
    if voting_start > Time.now
      "upcoming"
    else
      if voting_end > Time.now
        "ongoing"
      else
        "done"
      end
    end
  end

  def upcoming?
    voting_start > Time.now
  end

  def ongoing?
    voting_start < Time.now && voting_end > Time.now
  end

  def done?
    voting_start < Time.now && voting_end < Time.now
  end

  def default_gender
    if male_only?
      Contestant.genders["male"]
    elsif female_only?
      Contestant.genders["female"]
    end
  end

  def record_activity
    Activity.create(user: user, resource: self, created_at: created_at, updated_at: updated_at, action: 'created')
  end

  def self.log(msg)
    return puts msg if Rails.env.development?
    Rails.logger.info msg
  end

  def self.sanitize_votes(pagent_ids, delete = false)
    pagent_ids.each do |id|
      pageant = Pageant.find_by(id: id)
      next unless pageant.present?

      log ""
      log "Fix votes for Pageant##{pageant.id} - #{pageant.name}"

      mark_date = "2017-03-25".to_date
      date = pageant.voting_start.to_date
      date = mark_date if date < mark_date
      total_votes = 0
      total_votes_to_delete = 0
      total_votes_deleted = 0
      while date <= pageant.voting_end.to_date && date <= Date.today do
        offset = Time.now.strftime("%z").gsub("0","").gsub("-", "- INTERVAL ").gsub("+", "+ INTERVAL ")
        vote_count = Vote.where("contestant_id IN (?) AND DATE(created_at #{offset} HOUR) = DATE(?)", pageant.contestants.pluck(:id), date).count
        total_votes += vote_count
        if vote_count > 0
          log ""
          log "Sanitize Votes for #{date} - #{vote_count} vote#{'s' if vote_count > 1}"
          to_delete, deleted = Vote.sanitize_pageant(pageant.id, date, delete)
          if to_delete > 1
            log "Votes to Delete: #{to_delete}"
            log "Votes Deleted: #{deleted}"
            total_votes_to_delete += to_delete
            total_votes_deleted += deleted
          else
            log "No voting issues found!"
          end
        end

        date += 1.day
      end

      log ""
      log "Summary:"
      log "  Pageant: #{pageant.name}"
      log "  Schedule: #{pageant.voting_start.to_date} to #{pageant.voting_end.to_date}"
      log "  Total Votes: #{total_votes}"
      log "  Votes to Delete: #{total_votes_to_delete}"
      log "  Votes Deleted: #{total_votes_deleted}" if total_votes_deleted > 0
    end
  end

end

app/controllers/pageants_controller.rb
class PageantsController < ApplicationController
  before_filter :authenticate_user!, except: [:show, :current, :past, :all]
  before_filter :get_pageant_public_access, only: [:show]

  def index
    @pageants = current_user.pageants.not_deleted
    @q = @pageants.search(params[:q])
    @pageants = @q.result(distinct: true).page(params[:page])
  end

  def show
    if @pageant.published_status == "upcoming"
      @seconds_remaining = (@pageant.voting_start.to_time.in_time_zone(ENV['TIMEZONE']) - Time.now.in_time_zone(ENV['TIMEZONE'])).to_i
    else
      @seconds_remaining = (@pageant.voting_end.to_time.in_time_zone(ENV['TIMEZONE']) - Time.now.in_time_zone(ENV['TIMEZONE'])).to_i
    end
    @contestants = @pageant.contestants.not_deleted.sort_by_number
    if @pageant.male_and_female?
      @top_male = @pageant.top(5, "male")
      @top_female = @pageant.top(5, "female")
    else
      @top_contestants = @pageant.top(5)
    end
    @other_pageants = @pageant.other(4)
  end

  def new
    @pageant = current_user.pageants.new
  end

  def create
    @pageant = current_user.pageants.new(pageant_params)
    if @pageant.save
      current_user.prepare_wallet
      redirect_to pageant_path(@pageant), notice: "You have created new pageant."
    else
      render :new
    end
  end

  def edit
    get_pageant
  end

  def update
    get_pageant
    if @pageant.update_attributes(pageant_params)
      Activity.create(user: current_user, resource: @pageant, action: "updated")
      redirect_to @pageant, notice: "You have saved your changes."
    else
      render :edit
    end
  end

  def destroy
    get_pageant
    if @pageant.deleted!
      Activity.create(user: current_user, resource: @pageant, action: "deleted")
      redirect_to pageants_path, notice: "You have deleted a pageant."
    else
      redirect_to @pageant, notice: "Failed to deleate this pageant, please try again."
    end

  end

  def publish
    get_pageant
    if @pageant.published!
      Activity.create(user: current_user, resource: @pageant, action: "published")
      redirect_to @pageant, notice: "You have published this pageant."
    else
      redirect_to @pageant, notice: "Failed to publish this pageant, please try again."
    end
  end

  def unpublish
    get_pageant
    if @pageant.unpublished!
      Activity.create(user: current_user, resource: @pageant, action: "unpublished")
      redirect_to @pageant, notice: "You have unpublished this pageant."
    else
      redirect_to @pageant, notice: "Failed to unpublish this pageant, please try again."
    end
  end

  def current
    @pageants = Pageant.published.current.order(:voting_start)
    @q = @pageants.search(params[:q])
    @pageants = @q.result(distinct: true).page(params[:page])
  end

  def past
    @pageants = Pageant.published.past.order(voting_end: :desc)
    @q = @pageants.search(params[:q])
    @pageants = @q.result(distinct: true).page(params[:page])
  end

  def all
    @pageants = Pageant.published.order(:voting_start)
    @q = @pageants.search(params[:q])
    @pageants = @q.result(distinct: true).page(params[:page])
  end

  private

  def get_pageant
    if current_user.vip? || current_user.admin?
      @pageant = Pageant.find_by(id: params[:id])
    else
      @pageant = current_user.pageants.not_deleted.find_by(id: params[:id])
    end

    if @pageant.nil?
      flash[:error] = "Pageant not found!"
      redirect_to current_pageants_path and return
    end
  end

  def get_pageant_public_access
    @pageant = Pageant.not_deleted.find_by(id: params[:id]) # Allow everyone to vote

    if @pageant.nil?
      flash[:error] = "Pageant not found!"
      redirect_to current_pageants_path and return
    elsif !@pageant.published? && (!user_signed_in? || !@pageant.authorized?(current_user))
      redirect_to current_pageants_path and return
    end
  end

  def pageant_params
    params.require(:pageant).permit(:name, :description, :category, :voting_start, :voting_end, :show_votes, :boost_votes, :header, :banner, :thumb, :fb_button)
  end
end

app/helpers/pageants_helper.rb
module PageantsHelper
end

app/views/pageants/_form.html.haml
= f.error_notification
.row-fluid.form-fields.clearfix
  .col-sm-12.no-pad
    = f.input :name, label: "Pageant Name", input_html: {maxlength: 44}
  .col-sm-12.no-pad
    = f.input :description, label: "Pageant Description", input_html: {rows: 3, maxlength: 300}
  .col-sm-12.no-pad
    .form-group.optional.pageant_period
      .row-fluid
        .col-sm-12.no-pad
          %label.required.date{for: "pageant_period"}
            %abbr{title: "required"}= "*"
            = "Voting Period"
        .col-sm-6.no-pad
          = f.input :voting_start, as: "string", label: false, placeholder: "Select start date", input_html: {class: "datetime-basic"}
        .col-sm-6.no-pad
          = f.input :voting_end, as: "string", label: false, placeholder: "Select end date", input_html: {class: "datetime-basic"}
  .col-sm-12.no-pad
    = f.input :category, as: "radio_buttons", collection: Pageant.categories.collect{|k,v| [k.titleize,k]}, checked: f.object.category
  .col-sm-12.no-pad
    = f.input :show_votes, as: "radio_buttons", collection: [["Yes",true],["No",false]], checked: f.object.show_votes
  .col-sm-12.no-pad
    = f.input :boost_votes, as: "radio_buttons", label: raw("Boost Votes&nbsp;&nbsp;&nbsp;<a href=#{info_path('boost-votes')} target='_blank'>What is Boost Votes?</a>"), collection: [["Yes",true],["No",false]], checked: f.object.boost_votes
  .col-sm-12.no-pad
    = f.input :fb_button, label: "Facebook Like Button (CODE)", input_html: {rows: 3}, hint: "Paste the exact code generated by Facebook."
  .col-sm-12.no-pad
    = f.input :header, label: "Banner (Header)", hint: "Upload image with 1000 width x 300 height pixels"
    - if @pageant.present? && @pageant.header.exists?
      = image_tag @pageant.header.url(:cropped)
  .col-sm-12.no-pad
    = f.input :thumb, label: "Logo (For FB Share)", hint: "Upload image with 470 width x 245 height pixels"
    - if @pageant.present? && @pageant.thumb.exists?
      = image_tag @pageant.thumb.url(:cropped)
    - else
      = image_tag @pageant.thumb.url(:default_url)

  / .col-sm-6.no-pad
  /   = f.input :banner, hint: "Upload image with 690 width x 315 height dimension"

.form-buttons
  %p
    - if f.object.new_record?
      = f.submit "Create", class: "button"
      = link_to "Cancel", pageants_path, class: "btn btn-cancel"
    - else
      = f.submit "Save Changes", class: "button"
      = link_to "Cancel", f.object, class: "btn btn-cancel"

app/views/pageants/_side_list.html.haml
.row.add-top
  .col-sm-12
    .paged
      .row.clearfix
        .col-sm-12
          %table.table.table-striped.table-no-margin-bottom.table-slim-first-column
            %tr
              %th{colspan: 2}= title
            - contestants.each do |contestant|
              %tr
                %td= "##{contestant.number}"
                %td
                  = link_to contestant.name, pageant_contestant_path(pageant, contestant)
                  
                  - if contestant.pageant.show_votes?
                    - if contestant.pageant.done? && contestant.vote_count.present?
                      .pull-right= pluralize(contestant.vote_count, "vote")
                    - else
                      .pull-right= pluralize(contestant.votes_count, "vote")

app/views/pageants/all.html.haml
- content_for :title, "#{ENV['APP_NAME']} - All Pageants"
- content_for :info_url, all_pageants_url
- content_for :info_title, "All Pageants"
- content_for :info_description, "#{ENV['APP_NAME']} is an Online Voting Application for local, school, university and international pageants."
- content_for :info_image, "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "All Pageants", all_pageants_path, class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .search-list
            = search_form_for @q, url: all_pageants_path do |f|
              .input-group.input-group-sm.short-search
                = f.text_field :name_or_description_cont, placeholder: "Search Pageant"
                .input-group-btn
                  = f.button fa_icon("search"), class: "btn"
          - if @pageants.present?
            .row-fluid.clearfix
              - @pageants.each do |pageant|
                .col-sm-6.add-bottom
                  = render "pageants/pageant", pageant: pageant, with_status: true
              .col-sm-12.acenter= paginate @pageants
          - else
            .row-fluid.clearfix
              .col-sm-12
                .alert.alert-warning.acenter
                  No current pageants yet.
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/pageants/current.html.haml
- content_for :title, "#{ENV['APP_NAME']} - Current Pageants"
- content_for :info_url, current_pageants_url
- content_for :info_title, "Current Pageants"
- content_for :info_description, "#{ENV['APP_NAME']} is an Online Voting Application for local, school, university and international pageants."
- content_for :info_image, "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "Current Pageants", current_pageants_path, class: "active"
          %li>
            = link_to "Past Pageants", past_pageants_path
        .row-fluid.pad-top-bottom-medium.clearfix
          .search-list.hidden-xs
            = search_form_for @q, url: current_pageants_path do |f|
              .input-group.input-group-sm.short-search
                = f.text_field :name_or_description_cont, placeholder: "Search Pageant"
                .input-group-btn
                  = f.button fa_icon("search"), class: "btn"
          - if @pageants.present?
            .row-fluid.clearfix
              - @pageants.each do |pageant|
                .col-sm-6.add-bottom
                  = render "pageants/pageant", pageant: pageant, with_status: false
              .col-sm-12.acenter= paginate @pageants
          - else
            .row-fluid.clearfix
              .col-sm-12
                .alert.alert-warning.acenter
                  No current pageants for now.
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/pageants/edit.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      - if @pageant.header.present?
        .pageant-header
          = image_tag @pageant.header.url(:original)
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "Pageant Info", @pageant
          %li>
            = link_to "Settings", edit_pageant_path(@pageant), class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            = simple_form_for(@pageant, html: {class: "form", autocomplete: "off"}) do |f|
              = render "pageants/form", f: f
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/pageants/index.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "My Pageants", pageants_path, class: "active"
          %li>
            = link_to "Create a Pageant", new_pageant_path
        .row-fluid.pad-top-bottom-medium.clearfix
          .search-list.hidden-xs
            = search_form_for @q, url: pageants_path do |f|
              .input-group.input-group-sm.short-search
                = f.text_field :name_or_description_cont, placeholder: "Search Pageant"
                .input-group-btn
                  = f.button fa_icon("search"), class: "btn"
          - if @pageants.present?
            .row-fluid.clearfix
              - @pageants.each do |pageant|
                .col-sm-6.add-bottom
                  = render "pageants/pageant", pageant: pageant, with_status: true
            .row-fluid.acenter
              .span12= paginate @pageants
          - else
            .row-fluid.clearfix
              .col-sm-12
                .alert.alert-warning.acenter
                  - if @q.present?
                    No pageants found.
                  - else
                    No pageants yet.
                  = link_to "Click here to create one.", new_pageant_path, class: "no-wrap"
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/pageants/new.html.haml
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "My Pageants", pageants_path
          %li>
            = link_to "Create a Pageant", new_pageant_path, class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12
            = simple_form_for(@pageant, html: {class: "form", autocomplete: "off"}) do |f|
              = render "pageants/form", f: f
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/pageants/past.html.haml
- content_for :title, "#{ENV['APP_NAME']} - Past Pageants"
- content_for :info_url, past_pageants_url
- content_for :info_title, "Past Pageants"
- content_for :info_description, "#{ENV['APP_NAME']} is an Online Voting Application for local, school, university and international pageants."
- content_for :info_image, "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      .paged
        %ul.page-tabs.clearfix
          %li>
            = link_to "Current Pageants", current_pageants_path
          %li>
            = link_to "Past Pageants", past_pageants_path, class: "active"
        .row-fluid.pad-top-bottom-medium.clearfix
          .search-list.hidden-xs
            = search_form_for @q, url: past_pageants_path do |f|
              .input-group.input-group-sm.short-search
                = f.text_field :name_or_description_cont, placeholder: "Search Pageant"
                .input-group-btn
                  = f.button fa_icon("search"), class: "btn"
          - if @pageants.present?
            .row-fluid.clearfix
              - @pageants.each do |pageant|
                .col-sm-6.add-bottom
                  = render "pageants/pageant", pageant: pageant, with_status: false
              .col-sm-12.acenter= paginate @pageants
          - else
            .row-fluid.clearfix
              .col-sm-12
                .alert.alert-warning.acenter
                  No past pageants yet.
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      = render "shared/side_script"

app/views/pageants/show.html.haml
- content_for :title, "#{@pageant.name} - #{ENV['APP_NAME']}"
- content_for :info_url, pageant_url(@pageant)
- content_for :info_title, @pageant.name
- content_for :info_description, @pageant.description
- content_for :info_image, @pageant.thumb.present? ? asset_url(@pageant.thumb.url(:original)) : "http://#{ENV['DOMAIN_NAME']}/assets/#{ENV['OG_IMAGE']}"
.container-fluid.clearfix
  .row-fluid
    .col-sm-9.col-md-8.add-top-bottom-medium
      - if @pageant.header.present?
        .pageant-header
          = image_tag @pageant.header.url(:original)
      .paged
        - if @pageant.authorized?(current_user)
          %ul.page-tabs.clearfix
            %li>
              = link_to "Pageant Info", @pageant, class: "active"
            %li>
              = link_to "Settings", edit_pageant_path(@pageant)
        .row-fluid.pad-top-bottom-medium.clearfix
          .col-sm-12.acenter
            - unless @pageant.header.present?
              .page-title= @pageant.name

            - if @pageant.authorized?(current_user)
              .page-labels
                .label.label-default= @pageant.status.titleize
                .label.label-default= @pageant.category.titleize
                .label.label-default= @pageant.show_votes ? "Visible Votes" : "Hidden Votes"
            - if @pageant.authorized?(current_user)
              .page-controls
                = link_to edit_pageant_path(@pageant) do
                  = fa_icon "pencil"
                  = "Edit Pageant"
                = link_to new_pageant_contestant_path(@pageant) do
                  = fa_icon "plus"
                  = "Add Contestant"
                - if @pageant.published?
                  = link_to unpublish_pageant_path(@pageant), method: "post", data: {confirm: "Are you sure you want to unpublish this pagent?", confirm_subtitle: "Warning! This action will hide the pageant from other users."} do
                    = fa_icon "lock"
                    = "Unpublish"
                - else
                  = link_to publish_pageant_path(@pageant), method: "post", data: {confirm: "Are you sure you want to publish this pagent?", confirm_subtitle: "Warning! This action will allow anyone to view the pageant."} do
                    = fa_icon "unlock"
                    = "Publish"
                  = link_to pageant_path(@pageant), method: "delete", data: {confirm: "Are you sure you want to delete this pagent?", confirm_subtitle: "Warning! This action will delete all the related information."} do
                    = fa_icon "remove"
                    = "Delete"

            .page-info
              - if @pageant.description.present?
                .page-description= @pageant.description
              = "#{format_datetime(@pageant.voting_start)} to #{format_datetime(@pageant.voting_end)}"
              .page-labels
                - if @pageant.published?
                  - if @seconds_remaining > 0
                    - if @pageant.published_status == "upcoming"
                      .count-down-title= "Voting will start in (#{ENV['TIMEZONE_CODE']}):"
                    - else
                      .count-down-title= "Voting will end in (#{ENV['TIMEZONE_CODE']}):"
                    .counter_table{data: {date: "#{@pageant.published_status == "upcoming" ? @pageant.voting_start : @pageant.voting_end}", remaining_seconds: @seconds_remaining}}
                      .item-group
                        .item
                          .days 0
                          .label Days
                        .item
                          .hours 0
                          .label Hours
                        .item
                          .minutes 0
                          .label Minutes
                        .item
                          .seconds 0
                          .label Seconds
                - else
                  .count-down-title= "This pageant is not published."
              - if @pageant.published?
                = render "shared/social_share_buttons", term: "pageant"

          .row-fluid
            .col-sm-12
              %h3.title_main= "Contestants"
          = render "contestants/contestants", pageant: @pageant, contestants: @contestants
    .col-sm-3.col-md-4.add-top-bottom-medium
      = render "shared/side_images"
      - if @pageant.show_votes?
        - if @top_male.present?
          = render "pageants/side_list", pageant: @pageant, contestants: @top_male, title: "Top Male Contestants"
        - if @top_female.present?
          = render "pageants/side_list", pageant: @pageant, contestants: @top_female, title: "Top Female Contestants"
        - if @top_contestants.present?
          = render "pageants/side_list", pageant: @pageant, contestants: @top_contestants, title: "Top Contestants"
      - if @other_pageants.present?
        = render "pageants/other_pageants", pageants: @other_pageants, title: "Current Pageants"
      = render "shared/side_script"
#fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));